services:
  db:
    image: postgres:15
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data  # このパスで OK
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]  # -h localhost を追加
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp
      - bundle_data:/usr/local/bundle:cached
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: Asia/Tokyo
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password

volumes:
  postgres_data:
  bundle_data: