default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # ENV['DATABASE_URL'] があればそれを使う（なければローカルのpostgresを使う設定も可能だが、まずはこれだけでOK）
  url: <%= ENV['DATABASE_URL'] || 'postgres://localhost/pake_log_development' %>

development:
  <<: *default
  database: pake_log_development

test:
  <<: *default
  database: pake_log_test